# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4keigIB7--rLvzPlk2WkNHGDi4duEwn

EDA
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("/content/car_sales_data.csv")

df

print(pd.options.display.max_rows)#(pd.options.display.max_rows)

#what is the size of the data?
print('Dataset Size:',df.shape)

#print column index
df.columns

"""Inspect and understand your data"""

df.head()

df.tail()

#column dtypes and non-nulls
df.info()

#summary stats
df.describe()

"""Handling Missing and Duplicate Data"""

# count Null per columns
print("Missing value:", df.isnull().sum())

#drop rows with missing values
df.dropna(inplace=True)

"""Unique Function"""

unique_car_models=df['Car Model'].unique()
print(unique_car_models)

unique_car_make=df['Car Make'].unique()
print(unique_car_make)

unique_car_models=df['Car Model'].value_counts()
print(unique_car_models)

unique_car_make=df['Car Make'].value_counts()
print(unique_car_make)

#top 10 sales person
top_sales_person=df['Sale Price'].value_counts().head(10)
print(top_sales_person)

"""Most sold car model"""

Most_sold_car_model=df['Car Model'].value_counts().idxmax()
print("Most_sold_car_model:",Most_sold_car_model)

"""Most sold car model using (index())"""

Most_sold_car_model_1=df['Car Model'].value_counts().index[0]
print(Most_sold_car_model_1)

carr_1=df['Car Year'].corr(df['Sale Price'])
print(carr_1)

# find the salesperson who has highest comission earned
highest_commission=df.groupby('Salesperson')['Commission Earned'].sum()
highest_commission = highest_commission.sort_values(ascending=False)
print(highest_commission)

"""Yearly Sales"""

date_1=df.groupby('Car Year')['Sale Price'].sum().head()
print(date_1)

total_sales_by_year = df.groupby('Car Year')['Sale Price'].sum()
print(total_sales_by_year)

"""Data Visualization"""

yearly_sales = df.groupby('Car Year')['Sale Price'].sum()

# Calculate the percentage of sales for each year
yearly_sales_perc = yearly_sales / yearly_sales.sum() * 100

# Create a line chart to visualize the yearly sales percentage
plt.plot(yearly_sales_perc.index, yearly_sales_perc.values)
plt.xlabel('Year')
plt.ylabel('Percentage of Sales')
plt.title('Yearly Sales Percentage')
plt.show()

# Get value counts for car makes
car_make_counts = df['Car Make'].value_counts()

# Create a pie chart
fig, ax = plt.subplots(figsize=(5, 5))
ax.pie(car_make_counts, labels=car_make_counts.index, autopct='%1.1f%%', startangle=90)
ax.axis('equal')
ax.set_title('Distribution of Car Makes')
plt.show()

"""The top 5 Car Models"""

# Get value counts for car makes
car_make_counts = df['Car Model'].value_counts()

# Create a pie chart
fig, ax = plt.subplots(figsize=(5, 5))
ax.pie(car_make_counts, labels=car_make_counts.index, autopct='%1.1f%%', startangle=90)
ax.axis('equal')
ax.set_title('Distribution of Car Models')

plt.show()

import seaborn as sns
plt.figure(figsize=(5, 3))
sns.heatmap(df.select_dtypes(include=['number']).corr(), annot=True, cmap='coolwarm')
plt.show()

print(df.select_dtypes(include=['number']).corr())

"""Total salesperson_commission"""

Total_salesperson_commission=df.groupby('Salesperson')['Commission Earned'].sum().sort_values(ascending=False)
print(Total_salesperson_commission)

model_commission=df.groupby('Car Model')['Commission Earned'].sum().sort_values(ascending=False).head(1)
print(model_commission)